### ISSUE TITLE
Error (11547) - Unexpected server response: 200

### ISSUE THREAD

**Issue by reiniertc** [tickez/homebridge-unifi-guest-occupancy-sensor#1]
I've installed the plugin, entered my credentials and ip.address in the config.
I keep getting the error "Error (11547) - Unexpected server response: 200"
I've tested the ipaddress+port with my credentials on the cloudkey: that works fine. 

Any Clue how to fix this?

**Comment by tickez** [comment]
@reiniertc, I haven't been able to reproduce this, yet. As the plugin is extremely simple, I assume this is related to the Unifi websocket communication. Is there any reverse proxy or similar in between homebridge and the unifi controller?
