### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by yesnomaybewtf** [tickez/homebridge-unifi-guest-occupancy-sensor#4]
Got the following error:
`[8/12/2020, 7:51:05 PM] [Gast anwesend] ERROR: Failed to check occupancy: 401 - {"meta":{"rc":"error","msg":"api.err.NoSiteContext"},"data":[]}`

Config settings double checked, all ok. Unifi Controller ist running in a docker container.

**Comment by tickez** [comment]
This error occurs if you Unifi Site context is does not match the one in the config. By default it is "default". 
You find your site context name when you login to your Unifi controller and look at this part of the URL: manage/site/**default**/dashboard.

Set the "site": "default" property in the configuration to the same value.

**Comment by yesnomaybewtf** [comment]
Thank you.
My site is actually called sofie4,  but the url still says default.
Now its working!
