### ISSUE TITLE
Incompatible with new version of CloudKey+

### ISSUE THREAD

**Issue by SMJ0724** [tickez/homebridge-unifi-guest-occupancy-sensor#5]
After updating my CloudKey 2+'s firmware to 2.0.24, I am unable to use this plugin. The log shows:
```[29/12/2020, 14:31:53] [Guests are Present] ERROR: Failed to check occupancy: Cannot read property 'some' of undefined``` every few seconds.

I have tried changing the URL of the controller, but with the new firmware, authentication happens before accessing the network page, so I believe that is where the issue is occurring.

**Comment by tickez** [comment]
Similar report https://github.com/oznu/homebridge-unifi-occupancy-sensor/issues/27

**Comment by tickez** [comment]
I unfortunately have a standalone Controller running 6.0.43 and there it is still working so far.

**Comment by SMJ0724** [comment]
With the CloudKey 2+, the new firmware moves the key to the UnifiOS, the same as those using UDM Pro. This new OS has a different scheme for URLs and authentication. As reported in the other ticket, the Unifi Protect app is compatible with both the old controller (which uses the same URL scheme as the standalone controller that you are running) and the UnifiOS controller.

If I can be of any assistance, please let me know.

**Comment by tickez** [comment]
I released a new version 1.1.1 which should work with UnifiOS based devices. I switched the underlying library which communicates with the controller. Please let me know if this resolves the issue as I'm unable to verify myself.

**Comment by SMJ0724** [comment]
Looks like it's working perfectly for me! Thank you!

Happy New Year!

**Comment by tickez** [comment]
Happy New Year
